// Generated by gencpp from file nav_core/pos_vel_att_msg.msg
// DO NOT EDIT!


#ifndef NAV_CORE_MESSAGE_POS_VEL_ATT_MSG_H
#define NAV_CORE_MESSAGE_POS_VEL_ATT_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/Vector3.h>

namespace nav_core
{
template <class ContainerAllocator>
struct pos_vel_att_msg_
{
  typedef pos_vel_att_msg_<ContainerAllocator> Type;

  pos_vel_att_msg_()
    : header()
    , pos()
    , vel()  {
    }
  pos_vel_att_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)
    , vel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::nav_core::pos_vel_att_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_core::pos_vel_att_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pos_vel_att_msg_

typedef ::nav_core::pos_vel_att_msg_<std::allocator<void> > pos_vel_att_msg;

typedef boost::shared_ptr< ::nav_core::pos_vel_att_msg > pos_vel_att_msgPtr;
typedef boost::shared_ptr< ::nav_core::pos_vel_att_msg const> pos_vel_att_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_core::pos_vel_att_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav_core::pos_vel_att_msg_<ContainerAllocator1> & lhs, const ::nav_core::pos_vel_att_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav_core::pos_vel_att_msg_<ContainerAllocator1> & lhs, const ::nav_core::pos_vel_att_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_core::pos_vel_att_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_core::pos_vel_att_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_core::pos_vel_att_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a67d873ea38c38e5846a867f7cf7cb1b";
  }

  static const char* value(const ::nav_core::pos_vel_att_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa67d873ea38c38e5ULL;
  static const uint64_t static_value2 = 0x846a867f7cf7cb1bULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_core/pos_vel_att_msg";
  }

  static const char* value(const ::nav_core::pos_vel_att_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/PoseStamped pos\n"
"geometry_msgs/Vector3 vel\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::nav_core::pos_vel_att_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_vel_att_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_core::pos_vel_att_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_core::pos_vel_att_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_CORE_MESSAGE_POS_VEL_ATT_MSG_H
