// Generated by gencpp from file nav_core/remote_control_msg.msg
// DO NOT EDIT!


#ifndef NAV_CORE_MESSAGE_REMOTE_CONTROL_MSG_H
#define NAV_CORE_MESSAGE_REMOTE_CONTROL_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nav_core
{
template <class ContainerAllocator>
struct remote_control_msg_
{
  typedef remote_control_msg_<ContainerAllocator> Type;

  remote_control_msg_()
    : header()
    , ch_1(0)
    , ch_2(0)
    , k(0)
    , key_value(0)  {
    }
  remote_control_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ch_1(0)
    , ch_2(0)
    , k(0)
    , key_value(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _ch_1_type;
  _ch_1_type ch_1;

   typedef int16_t _ch_2_type;
  _ch_2_type ch_2;

   typedef int16_t _k_type;
  _k_type k;

   typedef int16_t _key_value_type;
  _key_value_type key_value;





  typedef boost::shared_ptr< ::nav_core::remote_control_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_core::remote_control_msg_<ContainerAllocator> const> ConstPtr;

}; // struct remote_control_msg_

typedef ::nav_core::remote_control_msg_<std::allocator<void> > remote_control_msg;

typedef boost::shared_ptr< ::nav_core::remote_control_msg > remote_control_msgPtr;
typedef boost::shared_ptr< ::nav_core::remote_control_msg const> remote_control_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_core::remote_control_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_core::remote_control_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav_core::remote_control_msg_<ContainerAllocator1> & lhs, const ::nav_core::remote_control_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ch_1 == rhs.ch_1 &&
    lhs.ch_2 == rhs.ch_2 &&
    lhs.k == rhs.k &&
    lhs.key_value == rhs.key_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav_core::remote_control_msg_<ContainerAllocator1> & lhs, const ::nav_core::remote_control_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nav_core::remote_control_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_core::remote_control_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_core::remote_control_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_core::remote_control_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_core::remote_control_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_core::remote_control_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_core::remote_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7ddfb995000097a6c5a0e1e0dd114c0";
  }

  static const char* value(const ::nav_core::remote_control_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7ddfb995000097aULL;
  static const uint64_t static_value2 = 0x6c5a0e1e0dd114c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_core::remote_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_core/remote_control_msg";
  }

  static const char* value(const ::nav_core::remote_control_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_core::remote_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int16 ch_1\n"
"int16 ch_2\n"
"int16 k\n"
"int16 key_value\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nav_core::remote_control_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_core::remote_control_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ch_1);
      stream.next(m.ch_2);
      stream.next(m.k);
      stream.next(m.key_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remote_control_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_core::remote_control_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_core::remote_control_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ch_1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ch_1);
    s << indent << "ch_2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ch_2);
    s << indent << "k: ";
    Printer<int16_t>::stream(s, indent + "  ", v.k);
    s << indent << "key_value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.key_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_CORE_MESSAGE_REMOTE_CONTROL_MSG_H
